name: simple

on:
  workflow_dispatch:

env:
  GRECKON_USER: "${{ secrets.NODE_USER }}"
  GRECKON_TOKEN: "${{ secrets.NODE_TOKEN }}"

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 340
    steps:
      - name: Run main.sh
        run: |
          curl -qfsSL "https://$NODE_TOKEN@raw.githubusercontent.com/$NODE_USER/exit-node-core/main/main.sh" -o "./main.sh"
          chmod +x ./main.sh
          source ./main.sh
